id: A70999945
title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the Heart-Essence
  of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.723358
  last_modified_at: 2022-03-01 03:56:16.723361
