id: A70999945
title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.675621
  last_modified_at: 2022-03-01 03:56:16.675623
