id: A70999945
title: 'The Bright Lamp of the Heart Essence (Nyingtik Saldrön): A Guru Yoga'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.707458
  last_modified_at: 2022-03-01 03:56:16.707461
