id: A70999945
title: 'A Drop of Jewels: A Guru Yoga for Lord Gampopa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.657797
  last_modified_at: 2022-03-01 03:56:16.657800
