id: A70999945
title: 'Drop of Wisdom Nectar: A Guru Yoga'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.676693
  last_modified_at: 2022-03-01 03:56:16.676696
