id: A70999945
title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.702069
  last_modified_at: 2022-03-01 03:56:16.702071
