id: A70999945
title: Guru Padma Yoga
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.678788
  last_modified_at: 2022-03-01 03:56:16.678790
