id: A70999945
title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the Three
  Deities of Long Life'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.667818
  last_modified_at: 2022-03-01 03:56:16.667821
