id: A70999945
title: 'A Drop of Moonlight: A Guru Yoga for Lord Mila'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.659915
  last_modified_at: 2022-03-01 03:56:16.659917
