id: A70999945
title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.662121
  last_modified_at: 2022-03-01 03:56:16.662124
