id: A70999945
title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.677665
  last_modified_at: 2022-03-01 03:56:16.677668
