id: A70999945
title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.703320
  last_modified_at: 2022-03-01 03:56:16.703323
