id: A70999945
title: Guru Yoga of the Great Omniscient One, Longchenpa
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.689921
  last_modified_at: 2022-03-01 03:56:16.689924
