id: A70999945
title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line Prayer'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.671127
  last_modified_at: 2022-03-01 03:56:16.671129
