id: A70999945
title: 'The Swift Bestowal of Blessings: A Guru Yoga'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.717681
  last_modified_at: 2022-03-01 03:56:16.717684
