id: A70999945
title: A Concise Guru Yoga
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.655510
  last_modified_at: 2022-03-01 03:56:16.655514
