id: A70999945
title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord Atiśa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.673336
  last_modified_at: 2022-03-01 03:56:16.673339
