id: A70999945
title: 'The Quintessential Blessing: A Guru Yoga'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.713575
  last_modified_at: 2022-03-01 03:56:16.713578
