id: A70999945
title: 'The Merry Sea of Blessings: A Guru Yoga of the Lord of Sages, Peerless Teacher
  of All, Including the Devas'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.711086
  last_modified_at: 2022-03-01 03:56:16.711090
