id: A70999945
title: Guru Yoga of Jetsün Shepa Dorje
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.684092
  last_modified_at: 2022-03-01 03:56:16.684095
