id: A70999945
title: Guru Yoga of Milarepa Shepa Dorje for Daily Practice
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.686546
  last_modified_at: 2022-03-01 03:56:16.686548
