id: A70999945
title: Guru Sādhana of Garab Dorje
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.680348
  last_modified_at: 2022-03-01 03:56:16.680351
