id: A70999945
title: Guru Yoga Focusing upon Noble KurukullÄ
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.681659
  last_modified_at: 2022-03-01 03:56:16.681662
