id: A70999945
title: 'The Profound Path of Guru Yoga: A Way to Freedom for the Fortunate'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.712442
  last_modified_at: 2022-03-01 03:56:16.712445
