id: A70999945
title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line Prayer
  (Addendum)'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.669661
  last_modified_at: 2022-03-01 03:56:16.669663
