id: A70999945
title: The Guru Yoga of the Profound Path
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.709741
  last_modified_at: 2022-03-01 03:56:16.709744
