id: A70999945
title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:16.705348
  last_modified_at: 2022-03-01 03:56:16.705351
